

---
kind: Namespace
apiVersion: v1
metadata:
  name: odoo
  labels:
    name: odoo
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-production
  namespace: odoo
  labels:
    app: odoo
spec:
  ports:
    - port: 8069
  selector:
    app: odoo
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: odoo-production
  namespace: odoo
  labels:
    app: odoo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo
        tier: frontend
    spec:
      containers:
        - image: gcr.io/affable-tangent-282111/odoo-production-builds/odoo
          name: odoo
          env:
          - name: USER
            value: odoo
          - name: PASSWORD
            value: password
          - name: HOST
            value: 10.4.2.32
          - name: PORT
            value: "5432"
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8069
              name: odoo
          volumeMounts:
          - name: odoo-prod-pvc
            mountPath: /var/lib/odoo
      volumes:
      - name: odoo-prod-pvc
        persistentVolumeClaim:
          claimName: odoo-prod-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/pv0003/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-prod-pvc
  namespace: odoo
  labels:
    app: odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
