 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: odoo-ingress
   namespace: odoo
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: odoo-prod.info
     http:
       paths:
       - path: /
         backend:
           serviceName: odoo-production
           servicePort: 8069
